/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ProdutoDAO;
import Model.Produto;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author leonardomonteiro
 */
public class MovimentarProduto extends javax.swing.JFrame {
    private java.util.List<Produto> produtos;
    private Produto produtoSelecionado;
    private DefaultTableModel modeloTabela;
    
    public MovimentarProduto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.prepararProdutos();
    }
    
    private void prepararProdutos () {
        ProdutoDAO conexao = new ProdutoDAO();
        conexao.getConnection();
        produtos = conexao.getProdutosList();
        
        modeloTabela = (DefaultTableModel) Produtos.getModel();

        for (Produto produto : produtos) {
            modeloTabela.addRow(new Object[]{produto.getId_produto(), produto.getNome_produto()});
        }
    }
    
    private void verificarCampos() {
        Boolean idValido = produtoSelecionado != null && produtoSelecionado.getId_produto() > 0;
        Boolean tipoSelecionado = jRadioButton1.isSelected() || jRadioButton2.isSelected();
        Boolean quantidadeValida = (Integer) QuantidadeSelecao.getValue() > 0;
        
        if (idValido && tipoSelecionado && quantidadeValida) {
            ConfirmarBotao.setEnabled(true);
        } else {
            ConfirmarBotao.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PesquisaProduto = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(0, 0, 100, 1);
        QuantidadeSelecao = new javax.swing.JSpinner(spinnerModel);
        CancelarBotao = new javax.swing.JButton();
        ConfirmarBotao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NomeProduto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EstoqueTotal = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Produtos = new javax.swing.JTable();

        setResizable(false);

        PesquisaProduto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                PesquisaProdutoInputMethodTextChanged(evt);
            }
        });
        PesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaProdutoActionPerformed(evt);
            }
        });
        PesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PesquisaProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisaProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PesquisaProdutoKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Entrada");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Saída");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de movimentação");

        jLabel3.setText("Quantidade");

        QuantidadeSelecao.setMinimumSize(new java.awt.Dimension(100, 100));
        QuantidadeSelecao.setPreferredSize(new java.awt.Dimension(100, 23));
        QuantidadeSelecao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                QuantidadeSelecaoStateChanged(evt);
            }
        });
        QuantidadeSelecao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantidadeSelecaoKeyReleased(evt);
            }
        });

        CancelarBotao.setText("Cancelar");
        CancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotaoActionPerformed(evt);
            }
        });

        ConfirmarBotao.setText("Confirmar");
        ConfirmarBotao.setEnabled(false);
        ConfirmarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarBotaoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Table.gridColor"));

        NomeProduto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NomeProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeProduto.setText("Produto Selecionado");

        jLabel4.setText("Estoque total:");

        EstoqueTotal.setText("0000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(EstoqueTotal))
                    .addComponent(NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EstoqueTotal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Produtos.getTableHeader().setReorderingAllowed(false);
        Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ProdutosMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(Produtos);
        if (Produtos.getColumnModel().getColumnCount() > 0) {
            Produtos.getColumnModel().getColumn(0).setResizable(false);
            Produtos.getColumnModel().getColumn(0).setPreferredWidth(5);
            Produtos.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(CancelarBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmarBotao)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PesquisaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuantidadeSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantidadeSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CancelarBotao)
                    .addComponent(ConfirmarBotao, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        verificarCampos();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void PesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaProdutoActionPerformed

    }//GEN-LAST:event_PesquisaProdutoActionPerformed

    private void searchTable(String searchText) {
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(modeloTabela);
        Produtos.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
    }
    
    private void ConfirmarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarBotaoActionPerformed
        ProdutoDAO conexao = new ProdutoDAO();
        conexao.getConnection();
        
        int novoEstoque = produtoSelecionado.getQuantidade_estoque();
        
        if (jRadioButton1.isSelected()) {
            novoEstoque += (int) QuantidadeSelecao.getValue();
        } else if (jRadioButton2.isSelected()) {
            novoEstoque -= (int) QuantidadeSelecao.getValue();
        }
        
        produtoSelecionado.setQuantidade_estoque(novoEstoque);
        conexao.UpdateProdutoBD(produtoSelecionado);
        
        buttonGroup1.clearSelection();
        QuantidadeSelecao.setValue(0);
        Produtos.clearSelection();
        
        this.NomeProduto.setText("Produto Selecionado");
        this.EstoqueTotal.setText("0000");
    }//GEN-LAST:event_ConfirmarBotaoActionPerformed

    private void CancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotaoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CancelarBotaoActionPerformed

    private void ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosMouseClicked

    }//GEN-LAST:event_ProdutosMouseClicked

    private void QuantidadeSelecaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_QuantidadeSelecaoStateChanged
        verificarCampos();
    }//GEN-LAST:event_QuantidadeSelecaoStateChanged

    private void PesquisaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisaProdutoKeyPressed
    }//GEN-LAST:event_PesquisaProdutoKeyPressed

    private void PesquisaProdutoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PesquisaProdutoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaProdutoInputMethodTextChanged

    private void PesquisaProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisaProdutoKeyTyped
    }//GEN-LAST:event_PesquisaProdutoKeyTyped

    private void PesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisaProdutoKeyReleased
        searchTable(PesquisaProduto.getText());
    }//GEN-LAST:event_PesquisaProdutoKeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        verificarCampos();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void QuantidadeSelecaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantidadeSelecaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeSelecaoKeyReleased

    private void ProdutosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosMouseReleased
        if (this.Produtos.getSelectedRow() >= 0) {
            int selecionado = this.Produtos.getSelectedRow();
            produtoSelecionado = produtos.get(selecionado);
            
            this.NomeProduto.setText(produtoSelecionado.getNome_produto());
            this.EstoqueTotal.setText(Integer.toString(produtoSelecionado.getQuantidade_estoque()));
        } else {
            this.NomeProduto.setText("Produto Selecionado");
            this.EstoqueTotal.setText("0000");
        }
        
        verificarCampos();
    }//GEN-LAST:event_ProdutosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MovimentarProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBotao;
    private javax.swing.JButton ConfirmarBotao;
    private javax.swing.JLabel EstoqueTotal;
    private javax.swing.JLabel NomeProduto;
    private javax.swing.JTextField PesquisaProduto;
    private javax.swing.JTable Produtos;
    private javax.swing.JSpinner QuantidadeSelecao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
